// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWatcher.Server.Models;

namespace MovieWatcher.Server.Migrations
{
    [DbContext(typeof(MovieTrackerContext))]
    partial class MovieTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("MovieWatcher.Server.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre");

                    b.Property<int>("Rating");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("WatchedOn");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Drama",
                            Rating = 4,
                            Title = "The Shawshank Redemption",
                            WatchedOn = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Drama",
                            Rating = 2,
                            Title = "The Godfather",
                            WatchedOn = new DateTime(2017, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Drama, Action",
                            Rating = 3,
                            Title = "The Dark Knight",
                            WatchedOn = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Drama",
                            Rating = 1,
                            Title = "The Godfather: Part II ",
                            WatchedOn = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Adventure, Drama, Fantasy",
                            Rating = 5,
                            Title = "The Lord of the Rings: The Return of the King",
                            WatchedOn = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Crime, Drama",
                            Rating = 3,
                            Title = "Pulp Fiction",
                            WatchedOn = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
